sudo: required

language: bash

services:
 - docker

env:
  - TAG=1.8
  - TAG=1.8.3
# - TAG=1.8.7
  - TAG=1.8.8
  - TAG=1.9
  - TAG=1.9.2
  - TAG=1.9.4
  - TAG=1.10.2
  - TAG=1.11
  - TAG=1.12
  - TAG=1.12.1
  - TAG=1.12.2
  - TAG=1.13.1
  - TAG=latest

install: 
    - docker pull bbriggs/bukkit

script:
  - ./test.sh
